export const PROJECTS_RAW = [
  {
    cat: 'finance',
    icon: 'lucide:shield-check',
    type: 'Production System',
    title: 'Fraud Risk Ops Platform',
    desc: 'Production-structured fraud risk platform for turning model scores into review-ready decisions through API contracts, policy-driven thresholds, audit logging, batch jobs, monitoring hooks, and an analyst review console.',
    priority: 100,
    problem:
      'Fraud scoring only becomes useful when analysts can act on model output through clear thresholds, review queues, audit trails, and monitoring signals.',
    approach: [
      'Separates model scoring, policy decisions, validation, audit trails, persistence, batch jobs, and monitoring so each layer can be reviewed independently.',
      'Uses configurable threshold policies to turn calibrated risk scores into approve, decline, or review actions without changing the model artifact.',
      'Pairs the FastAPI inference service with an analyst-facing Streamlit console for score review, diagnostics, and operational decision support.',
    ],
    signals: [
      'Reference validation: RF F1 0.882 · XGBoost F1 0.876.',
      'Operational signals: PR-AUC / ROC-AUC review · calibration checks · review-volume KPIs · approvals/declines monitoring · drift cues · SHAP explanations.',
    ],
    stack: [
      'Python',
      'FastAPI',
      'Pydantic',
      'Streamlit',
      'scikit-learn',
      'XGBoost',
      'Docker',
      'Redis',
      'SQLite',
      'MLflow',
      'Prometheus',
      'Grafana',
      'pytest',
    ],
    tags: [
      'Fraud Detection',
      'Risk Scoring',
      'Model Serving',
      'Threshold Policies',
      'Audit Logging',
      'Monitoring',
    ],
    repo: 'fraud-risk-ops-platform',
    imageBase: 'Fraud Risk Ops Platform',
    impact: 'Reference validation: RF F1 0.882 · XGBoost F1 0.876.',
  },
  {
    cat: 'genai',
    icon: 'lucide:search-check',
    type: 'RAG Evaluation',
    title: 'RAG QA Command Center',
    desc: 'RAG QA evaluation workspace for reviewing retrieval quality, hallucination exposure, configuration trade-offs, trace evidence, and review-policy simulation.',
    priority: 99,
    problem:
      'RAG systems are hard to trust when retrieval failures, hallucination exposure, and configuration trade-offs are hidden inside raw logs.',
    approach: [
      'Turns QA logs and retrieval traces into an operator review flow covering quality posture, retrieval diagnostics, risk slices, configuration comparison, and trace review.',
      'Uses policy simulation to inspect how review thresholds change workload and quality posture before rollout decisions.',
      'Exports evidence-style artifacts so RAG quality review can be repeated and shared instead of judged from isolated examples.',
    ],
    signals: [
      'Evaluation asset: 3,824 QA eval runs · 93,375 retrieval events.',
      'Correctness-risk baseline: Logistic Regression ROC-AUC 0.755.',
      'Review signals: retrieval metrics · groundedness review · citation coverage · trace inspection · latency signals · token/cost budgets.',
    ],
    stack: ['Python', 'Streamlit', 'Plotly', 'Pandas', 'FAISS', 'pgvector', 'Docker', 'pytest'],
    tags: [
      'RAG Evaluation',
      'Retrieval Diagnostics',
      'Hallucination Review',
      'Trace Review',
      'Policy Simulation',
    ],
    repo: 'rag-qa-command-center',
    imageBase: 'RAG QA Command Center',
    linkLabel: 'View Repo',
    alt: {
      href: 'https://github.com/tarekmasryo/rag-qa-logs-and-corpus',
      label: 'Eval Asset',
    },
    impact:
      '3,824 QA eval runs · 93,375 retrieval events · ROC-AUC 0.755 correctness-risk baseline.',
  },
  {
    cat: 'genai',
    icon: 'lucide:activity',
    type: 'LLMOps',
    title: 'LLMOps Telemetry Command Center',
    desc: 'LLMOps telemetry command center for reviewing reliability, latency, cost, routing-policy behavior, triage thresholds, drift signals, model health, and evidence exports.',
    priority: 98,
    problem:
      'LLM applications need more than aggregate dashboards; operators need telemetry that explains reliability, cost, drift, routing behavior, and triage pressure.',
    approach: [
      'Organizes offline interaction telemetry into operator-facing views for operating posture, risk hotspots, routing scenarios, triage simulation, and review queues.',
      'Separates validation, quality review, drift inspection, and evidence export so operational issues remain visible and auditable.',
      'Uses routing and triage views to compare policy behavior before changing thresholds or model-routing rules.',
    ],
    signals: [
      'Telemetry asset: 9,000 interactions · 1,595 sessions · 438 users.',
      'Operational signals: quality metrics · human review flags · latency · error rates · failure categories · cost burn · drift signals · routing behavior · triage thresholds.',
    ],
    stack: ['Python', 'Streamlit', 'Plotly', 'Pandas', 'MLflow', 'Docker', 'pytest'],
    tags: ['LLMOps', 'Telemetry', 'Observability', 'Drift Signals', 'Routing Review', 'Triage'],
    repo: 'llmops-telemetry-command-center',
    imageBase: 'LLMOps Telemetry Command Center',
    linkLabel: 'View Repo',
    alt: {
      href: 'https://github.com/tarekmasryo/llm-production-telemetry',
      label: 'Telemetry Asset',
    },
    impact: '9,000 interactions · 1,595 sessions · 438 users.',
  },
  {
    cat: 'social',
    icon: 'lucide:message-square-text',
    type: 'NLP Workspace',
    title: 'Advanced ML Sentiment Lab',
    desc: 'Interactive ML review lab for sentiment classification with TF-IDF word/char features, multi-model training, ROC/PR-AUC evaluation, threshold tuning, error analysis, and live prediction.',
    priority: 97,
    problem:
      'A sentiment classifier is difficult to trust when model comparison, threshold tuning, error review, and live prediction are scattered across notebook cells.',
    approach: [
      'Builds a structured review workflow around data loading, validation, leakage-safe training, model comparison, and artifact export.',
      'Combines TF-IDF word and character n-gram pipelines to compare complementary text representations.',
      'Adds threshold-aware prediction and error review so users can inspect false positives and false negatives rather than relying on a fixed 0.5 cutoff.',
    ],
    signals: [
      'Evaluation signals: ROC/PR evaluation · model comparison · threshold tuning · confusion matrices · error analysis · live inference checks.',
      'Modeling coverage: Logistic Regression · Naive Bayes · Random Forest · tree-based classifiers where supported.',
    ],
    stack: ['Python', 'Streamlit', 'Plotly', 'scikit-learn', 'TF-IDF', 'Docker', 'pytest'],
    tags: [
      'NLP',
      'Sentiment Analysis',
      'Text Classification',
      'Threshold Tuning',
      'Error Analysis',
    ],
    repo: 'advanced-ml-sentiment-lab',
    imageBase: 'Advanced ML Sentiment Lab',
    impact:
      'Text classification · model comparison · ROC/PR evaluation · threshold tuning · error analysis.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:brain',
    type: 'Decision App',
    title: 'Health Intelligence Platform',
    desc: 'Health intelligence dashboard for digital wellbeing signals, risk scoring, cohort KPIs, threshold diagnostics, trends, and scenario simulation.',
    priority: 96,
    problem:
      'Digital wellbeing data needs to be translated into cohort-level risk views, threshold diagnostics, and scenario exploration before it becomes useful for decisions.',
    approach: [
      'Structures behavioral and wellbeing signals into KPI cards, cohort comparisons, trend views, and risk-scoring summaries.',
      'Adds threshold diagnostics and scenario simulation so users can compare practical intervention rules instead of only reading charts.',
    ],
    signals: [
      'Operational signals: wellbeing KPI summaries · segment views · trend patterns · risk scoring · threshold diagnostics · scenario simulation.',
      'Review focus: digital wellbeing · cohort analysis · risk prioritization · decision-oriented dashboarding.',
    ],
    stack: ['Python', 'Streamlit', 'Plotly', 'Pandas', 'XGBoost'],
    tags: ['Health Analytics', 'Wellbeing Risk', 'KPI Dashboard', 'Scenario Simulator'],
    repo: 'health-intelligence-platform',
    imageBase: 'Health Intelligence Platform',
    impact:
      'Digital wellbeing · risk scoring · cohort KPIs · threshold diagnostics · scenario simulation.',
  },
  {
    cat: 'social',
    icon: 'lucide:video',
    type: 'Decision App',
    title: 'Short Video Intelligence Dashboard',
    desc: 'Short-form video intelligence dashboard for virality scoring, engagement metrics, creator leaderboards, timing patterns, and segment benchmarks.',
    priority: 95,
    problem:
      'Short-form content performance is noisy; creators and operators need quick ways to compare momentum, engagement, timing, and segment behavior.',
    approach: [
      'Turns content-performance data into comparison views for virality signals, engagement review, creator analysis, timing patterns, and segment prioritization.',
      'Uses interactive filters and benchmarks to make platform and content slices easier to inspect without manual spreadsheet work.',
    ],
    signals: [
      'Operational signals: virality indicators · engagement KPIs · creator leaderboards · timing patterns · content comparison views · segment benchmarks.',
      'Review focus: creator insights · short-video analytics · prioritization signals.',
    ],
    stack: ['Python', 'Streamlit', 'Plotly', 'Pandas'],
    tags: ['Short Video', 'Social Analytics', 'Virality Analytics', 'Creator Insights'],
    repo: 'short-video-intelligence-dashboard',
    imageBase: 'Short Video Intelligence Dashboard',
    impact:
      'Virality scoring · engagement KPIs · creator comparison · timing patterns · segment benchmarks.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:building-2',
    type: 'Healthcare ML',
    title: 'Hospital Deterioration — Next 12h Early Warning',
    desc: 'Clinical deterioration early-warning baseline for next-12h patient risk with leak-safe evaluation, model comparison, and threshold/policy tables.',
    priority: 90,
    problem:
      'Clinical early-warning models need leakage-safe time-aware evaluation and threshold regimes that match different alerting policies.',
    approach: [
      'Uses time-aware validation to keep next-12h deterioration prediction aligned with realistic clinical review settings.',
      'Compares baseline and boosted models before selecting operating thresholds for balanced, high-recall, and low-alert regimes.',
      'Frames output as triage-oriented risk scores and threshold tables rather than a single model score.',
    ],
    signals: [
      'Held-out performance: XGBoost ROC-AUC 0.9519 · PR-AUC 0.6909.',
      'Operational signals: Logistic Regression and HistGradientBoosting baselines · threshold policy tables · balanced / high-recall / low-alert regimes · cohort/error slices.',
    ],
    stack: ['Python', 'scikit-learn', 'XGBoost', 'Pandas', 'Jupyter'],
    tags: ['Healthcare ML', 'Early Warning', 'Patient Deterioration', 'Threshold Tuning'],
    repo: 'hospital-deterioration-next-12h-early-warning-baseline',
    imageBase: 'hospital-deterioration-next-12h-early-warning',
    alt: {
      href: 'https://github.com/tarekmasryo/hospital-deterioration-dataset',
      label: 'Dataset',
    },
    impact: 'ROC-AUC 0.9519 · PR-AUC 0.6909.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:activity',
    type: 'ML Pipeline',
    title: 'Pima Diabetes Pipeline',
    desc: 'End-to-end diabetes risk prediction pipeline with EDA, feature engineering, calibration, cost-aware thresholds, and deployable artifacts.',
    priority: 88,
    problem:
      'A diabetes-risk workflow needs reliable preprocessing, calibrated probabilities, and clear threshold trade-offs before it can be packaged as a reusable ML artifact.',
    approach: [
      'Builds a compact tabular ML pipeline around schema checks, missingness review, leak-safe validation, and repeatable inference.',
      'Uses calibrated probability outputs and threshold comparison so risk scores can be interpreted as decision inputs.',
      'Packages validation logic, metrics, and artifacts so the workflow can be rerun and handed off cleanly.',
    ],
    signals: [
      'Evaluation signals: ROC-AUC / PR-AUC review · calibration checks · threshold trade-offs · schema and missingness checks.',
      'Delivery signals: reproducible pipeline · deployable artifacts · CI-ready project structure.',
    ],
    stack: ['Python', 'scikit-learn', 'Pandas', 'Pydantic', 'pytest', 'GitHub Actions'],
    tags: ['Clinical Risk', 'ML Pipeline', 'Calibration', 'Reproducible ML'],
    repo: 'pima-diabetes-pipeline',
    imageBase: 'pima-diabetes-pipeline',
    impact: 'Schema validation · calibrated probabilities · threshold trade-offs.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:heart-pulse',
    type: 'ML Pipeline',
    title: 'Predicting Wellbeing Risk',
    desc: 'Digital habits to wellbeing-risk modeling workflow with calibrated risk scoring, cost-aware thresholding, and deployable artifacts.',
    priority: 86,
    problem:
      'Digital behavior signals become more useful when they are converted into calibrated wellbeing-risk scores and threshold policies.',
    approach: [
      'Models digital habits as tabular behavioral features for risk scoring and segment-level review.',
      'Compares Logistic Regression, Random Forest, and XGBoost-style baselines before selecting threshold behavior.',
      'Packages the workflow around calibrated scores and cost-aware threshold discussion rather than raw classification only.',
    ],
    signals: [
      'Evaluation signals: model comparison · calibration review · threshold tuning · digital behavior slices.',
      'Review focus: digital behavior · wellbeing risk · risk scoring · reproducible notebook workflow.',
    ],
    stack: ['Python', 'scikit-learn', 'XGBoost', 'Pandas', 'Jupyter'],
    tags: ['Wellbeing Risk', 'Calibration', 'Threshold Tuning', 'Digital Behavior'],
    repo: 'predicting-wellbeing-risk',
    imageBase: 'Predicting Wellbeing Risk',
    alt: {
      href: 'https://github.com/tarekmasryo/digital-lifestyle-benchmark-dataset',
      label: 'Dataset',
    },
    impact: 'Digital behavior · risk scoring · calibration · threshold tuning.',
  },

  {
    cat: 'finance',
    icon: 'lucide:credit-card',
    type: 'ML Pipeline',
    title: 'Credit Card Fraud Detection',
    desc: 'Cost-aware credit card fraud detection pipeline with time-based split, probability calibration, and AUPRC-first threshold tuning.',
    priority: 82,
    problem:
      'Fraud detection on imbalanced data requires time-aware validation, calibrated probabilities, and AUPRC-first threshold decisions rather than accuracy-driven reporting.',
    approach: [
      'Uses a time-based split to reduce unrealistic leakage between earlier and later transaction behavior.',
      'Evaluates models with an imbalanced-classification lens and prioritizes AUPRC plus threshold trade-offs.',
      'Frames output around business-aligned thresholds so review volume and fraud capture can be compared explicitly.',
    ],
    signals: [
      'Evaluation signals: AUPRC-first evaluation · time-based validation · probability calibration · class-imbalance handling · business-aligned thresholding.',
      'Modeling coverage: Logistic Regression · Random Forest · XGBoost.',
    ],
    stack: ['Python', 'scikit-learn', 'XGBoost', 'Random Forest', 'Logistic Regression', 'Pandas'],
    tags: ['Credit Card Fraud', 'FinTech', 'Calibration', 'Threshold Tuning'],
    repo: 'creditcard-fraud-detection',
    imageBase: 'Credit Card Fraud Detection',
    impact: 'AUPRC-first fraud pipeline with calibrated probabilities and threshold tuning.',
  },
  {
    cat: 'social',
    icon: 'lucide:message-square-warning',
    type: 'NLP Pipeline',
    title: 'SMS Spam Detection',
    desc: 'SMS spam detection pipeline using word/char TF-IDF, calibrated Linear SVM, nested CV, threshold tuning, explainability, and robustness tests.',
    priority: 80,
    problem:
      'Spam filtering needs a careful false-positive / false-negative balance because blocking legitimate messages can be more damaging than missing some spam.',
    approach: [
      'Combines word and character TF-IDF features to capture both phrase-level and pattern-level spam signals.',
      'Uses calibrated Linear SVM-style scoring with nested validation and threshold review.',
      'Adds explainability and robustness checks so model behavior can be inspected beyond headline metrics.',
    ],
    signals: [
      'Evaluation signals: precision/recall trade-offs · false-positive review · false-negative review · calibration · robustness checks · explainability.',
      'Review focus: spam filtering · text classification · threshold-aware decisions.',
    ],
    stack: ['Python', 'scikit-learn', 'TF-IDF', 'Linear SVM', 'Jupyter'],
    tags: ['NLP', 'SMS Spam', 'Text Classification', 'Linear SVM'],
    repo: 'sms-spam-detection',
    imageBase: 'SMS Spam Detection',
    impact: 'Calibrated spam detection with nested CV and robustness checks.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:microscope',
    type: 'ML Pipeline',
    title: 'Cancer Risk Prediction',
    desc: 'Cancer risk classification pipeline with leakage detection, stratified CV, model benchmarking, and interpretability.',
    priority: 78,
    problem:
      'Healthcare-style risk modeling must separate usable predictive inputs from leakage-prone derived fields before any model comparison is credible.',
    approach: [
      'Identifies leakage risk in derived fields and excludes risk-derived features from training.',
      'Uses stratified cross-validation to compare models across cancer-type and risk-level prediction tasks.',
      'Adds interpretability views so feature behavior and model errors can be reviewed instead of only reporting scores.',
    ],
    signals: [
      'Evaluation signals: leakage checks · stratified CV · macro-F1 evaluation · model benchmarking · permutation importance.',
      'Review focus: healthcare-style classification · interpretable modeling · realistic feature separation.',
    ],
    stack: ['Python', 'scikit-learn', 'XGBoost', 'Pandas', 'Jupyter'],
    tags: ['Cancer Risk', 'Healthcare ML', 'Data Leakage', 'Interpretability'],
    repo: 'cancer-risk-prediction',
    imageBase: 'Cancer Risk Prediction',
    alt: {
      href: 'https://github.com/tarekmasryo/cancer-risk-factors-data',
      label: 'Data Repo',
    },
    impact:
      'Leakage-aware cancer risk classification with model benchmarking and interpretability.',
  },
  {
    cat: 'analytics',
    icon: 'lucide:car',
    type: 'ML Pipeline',
    title: 'Road Accident Risk',
    desc: 'Road accident risk regression project using LightGBM, residual XGBoost, and model blending for stable OOF RMSE.',
    priority: 76,
    problem:
      'Road-segment risk modeling needs stable regression behavior and interpretable safety features, not just a leaderboard-style fitted model.',
    approach: [
      'Combines LightGBM, residual XGBoost, and NNLS blending to improve fold stability and reduce unstable predictions.',
      'Uses interpretable risk features such as curvature-speed interactions, accident-per-lane signals, and critical-zone flags.',
      'Frames the residual learner around what the safety prior misses so the workflow stays easier to explain.',
    ],
    signals: [
      'Evaluation signals: OOF RMSE · LightGBM baseline · residual XGBoost · NNLS blend · segment-level risk review.',
      'Review focus: road safety · calibrated risk scoring · interpretable feature engineering.',
    ],
    stack: ['Python', 'LightGBM', 'XGBoost', 'Pandas', 'scikit-learn'],
    tags: ['Road Safety', 'Accident Risk', 'Regression', 'Model Blending'],
    repo: 'road-accident-risk-ps5e10',
    imageBase: 'Road Accident Risk',
    alt: {
      href: 'https://www.kaggle.com/code/tarekmasryo/road-accident-risk-ps5e10',
      label: 'Kaggle Notebook',
    },
    impact: 'LightGBM + residual XGBoost + NNLS blend for stable OOF RMSE.',
  },
  {
    cat: 'finance',
    icon: 'lucide:banknote',
    type: 'ML Pipeline',
    title: 'Loan Payback Prediction',
    desc: 'Credit scoring project focused on feature engineering, leak-safe encodings, XGBoost/LightGBM modeling, stacked ensembling, and reusable artifacts.',
    priority: 74,
    problem:
      'Credit scoring workflows need leak-safe feature engineering, cross-validation, and model comparison before predictions can support lending decisions.',
    approach: [
      'Builds engineered credit-risk features with attention to leakage-prone encodings.',
      'Compares XGBoost and LightGBM-style models before stacking/ensembling decisions.',
      'Packages reusable artifacts so the workflow can be inspected and rerun.',
    ],
    signals: [
      'Evaluation signals: cross-validation · leak-safe encodings · XGBoost / LightGBM comparison · stacked ensemble · reusable artifacts.',
      'Review focus: credit scoring · binary classification · model selection.',
    ],
    stack: ['Python', 'XGBoost', 'LightGBM', 'Pandas', 'scikit-learn'],
    tags: ['Credit Scoring', 'Binary Classification', 'Model Selection', 'LightGBM'],
    repo: 'loan-payback-ps5e11',
    imageBase: 'Loan Payback Prediction',
    alt: {
      href: 'https://www.kaggle.com/code/tarekmasryo/loan-payback-ps5e11/notebook',
      label: 'Kaggle Notebook',
    },
    impact:
      'Credit scoring with leak-safe encodings, boosted models, and stacked ensemble comparison.',
  },
  {
    cat: 'analytics',
    icon: 'lucide:chart-line',
    type: 'ML Pipeline',
    title: 'Superstore Sales Prediction',
    desc: 'Superstore sales analysis and prediction workflow combining EDA, KPI insights, profit prediction, and time-series forecasting.',
    priority: 73,
    problem:
      'Retail sales data needs both business-facing KPI analysis and predictive modeling so profit drivers and forecast patterns can be reviewed together.',
    approach: [
      'Combines EDA, KPI views, profit prediction, and time-series forecasting in one analysis workflow.',
      'Uses Random Forest/XGBoost-style regression for profit prediction and Holt-Winters forecasting for temporal patterns.',
      'Frames outputs around business interpretation rather than model scores alone.',
    ],
    signals: [
      'Evaluation signals: sales analytics · KPI analysis · profit prediction · Random Forest/XGBoost · Holt-Winters forecasting.',
      'Review focus: regression · forecasting · retail performance insights.',
    ],
    stack: ['Python', 'Pandas', 'scikit-learn', 'XGBoost', 'Time Series'],
    tags: ['Sales Analytics', 'Regression', 'Forecasting', 'KPI Insights'],
    repo: 'superstore-sales-prediction',
    imageBase: 'Superstore Sales Prediction',
    impact: 'Sales analytics · profit prediction · time-series forecasting.',
  },
  {
    cat: 'genai',
    icon: 'lucide:database',
    type: 'Evaluation Asset',
    title: 'RAG QA Logs & Corpus',
    desc: 'Multi-table RAG QA telemetry and evaluation asset for retrieval attribution, hallucination-risk slicing, and quality × cost × latency trade-offs.',
    priority: 70,
    problem:
      'RAG evaluation needs multi-table evidence covering questions, retrieval events, corpus documents, and operational signals instead of isolated prompt examples.',
    approach: [
      'Provides QA logs, corpus data, retrieval traces, evaluation labels, and operational telemetry for retrieval/reranking analysis.',
      'Structures the asset so hallucination-risk slicing and quality × cost × latency trade-offs can be reviewed systematically.',
      'Supports downstream dashboards and notebooks that need source-grounded evidence rather than ad hoc examples.',
    ],
    signals: [
      'Evaluation asset: 3,824 QA eval runs · 93,375 retrieval events.',
      'Correctness-risk baseline: Logistic Regression ROC-AUC 0.755.',
      'Operational signals: retrieval metrics · recall@k / MRR / nDCG where applicable · groundedness review · citation coverage · latency · token/cost budgets.',
    ],
    stack: ['Python', 'Pandas', 'FAISS', 'pgvector', 'Jupyter'],
    tags: ['RAG Evaluation', 'Retrieval Traces', 'Hallucination Risk', 'Cost Analysis'],
    repo: 'rag-qa-logs-and-corpus',
    imageBase: 'RAG QA Logs & Corpus Data',
    alt: {
      href: 'https://github.com/tarekmasryo/rag-qa-logs-corpus-data',
      label: 'Data Repo',
    },
    impact: '3,824 QA eval runs · 93,375 retrieval events.',
  },
  {
    cat: 'genai',
    icon: 'lucide:activity',
    type: 'Evaluation Asset',
    title: 'LLM Production Telemetry Dataset & Notebook',
    desc: 'Production-style LLM telemetry dataset and notebook for telemetry validation, SLO/budget burn, routing backtests, drift checks, triage policy, and review-ready operational artifacts.',
    priority: 68,
    problem:
      'LLM operations teams need structured telemetry data to review quality, latency, failures, routing behavior, cost, and drift without relying on anecdotal traces.',
    approach: [
      'Models LLM observability as a repeatable evaluation asset: validate telemetry, inspect quality and cost, compare routing behavior, and track drift.',
      'Exports review-ready artifacts for SLO/budget burn, routing backtests, triage policy, and model health inspection.',
      'Keeps dataset and notebook structure aligned so analysis can be reproduced and extended.',
    ],
    signals: [
      'Telemetry asset: 9,000 interactions · 1,595 sessions · 438 users.',
      'Operational signals: quality metrics · human review flags · latency · error rates · failure categories · cost per request · cost per conversation · budget burn · drift checks.',
    ],
    stack: ['Python', 'Pandas', 'Plotly', 'MLflow', 'Jupyter'],
    tags: ['LLMOps', 'Observability', 'Telemetry', 'Drift Detection', 'Cost Analysis'],
    repo: 'llm-production-telemetry',
    imageBase: 'llm-production-telemetry-dataset',
    alt: {
      href: 'https://www.kaggle.com/datasets/tarekmasryo/llm-system-ops-production-telemetry-and-sft',
      label: 'Kaggle Dataset',
    },
    impact: '9,000 interactions · 1,595 sessions · 438 users.',
  },
  {
    cat: 'analytics',
    icon: 'lucide:plug',
    type: 'Dataset',
    title: 'Global EV Infra Dataset',
    desc: 'Global EV charging infrastructure dataset for station coverage, connector analysis, power categories, and EV infrastructure analytics.',
    priority: 66,
    problem:
      'EV infrastructure analysis needs standardized station, connector, power-class, and country-level fields before coverage and network-planning questions can be answered.',
    approach: [
      'Standardizes charging-site records into an analysis-ready dataset for station coverage, connector analysis, and power-category review.',
      'Supports geospatial and market-slice analysis through consistent country and infrastructure fields.',
      'Keeps dataset structure suitable for both dashboards and notebook-based exploration.',
    ],
    signals: [
      'Data scale: 242,417 charging sites across 121 countries.',
      'Operational signals: regional coverage · connector distribution · power-class breakdowns · infrastructure comparison views.',
    ],
    stack: ['Python', 'Pandas', 'Geospatial Data', 'Dataset'],
    tags: ['EV Charging', 'Geospatial Data', 'Infrastructure Analytics', 'Dataset'],
    repo: 'global-ev-infra-dataset',
    imageBase: 'global-ev-infra-dataset',
    alt: {
      href: 'https://www.kaggle.com/datasets/tarekmasryo/global-ev-charging-stations',
      label: 'Kaggle Dataset',
    },
    impact: '242,417 charging sites across 121 countries.',
  },
  {
    cat: 'social',
    icon: 'lucide:trending-up',
    type: 'Dataset',
    title: 'YouTube/TikTok Trends Dataset 2025',
    desc: 'Analysis-ready dataset for global YouTube Shorts and TikTok trends, with raw files, ML-ready tables, rollups, data dictionary, standardized schemas, and deduplicated IDs.',
    priority: 64,
    problem:
      'Short-form trend analysis needs clean, deduplicated, analysis-ready tables before creators or analysts can compare engagement patterns across platforms and countries.',
    approach: [
      'Provides raw files, ML-ready tables, rollups, data dictionary, standardized schemas, and deduplicated IDs.',
      'Organizes platform, creator, hashtag, country, and engagement fields for trend exploration and dashboard workflows.',
    ],
    signals: [
      'Operational signals: engagement metrics · trend patterns · creator analysis · hashtags · platform/country breakdowns · short-form dynamics.',
      'Review focus: YouTube Shorts · TikTok · engagement analytics · trend mining.',
    ],
    stack: ['Python', 'Pandas', 'Data Dictionary', 'Dataset'],
    tags: ['YouTube Shorts', 'TikTok', 'Engagement Analytics', 'Trend Mining'],
    repo: 'youtube-tiktok-trends-dataset-2025',
    imageBase: 'youtube-tiktok-trends-dataset-2025',
    alt: {
      href: 'https://www.kaggle.com/datasets/tarekmasryo/youtube-shorts-and-tiktok-trends-2025',
      label: 'Kaggle Dataset',
    },
    impact: 'Short-form trend dataset with ML-ready tables and standardized schemas.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:heart',
    type: 'Dataset',
    title: 'Digital Lifestyle Benchmark Dataset',
    desc: 'Synthetic digital lifestyle benchmark dataset for wellbeing-risk modeling and reproducible notebooks.',
    priority: 62,
    problem:
      'Wellbeing-risk experiments need a compact benchmark dataset with behavioral signals and clear target structure for reproducible modeling workflows.',
    approach: [
      'Provides synthetic digital lifestyle records with documented feature structure for wellbeing-risk modeling.',
      'Keeps the dataset small and reproducible so notebooks can run quickly while still supporting cohort and risk-signal analysis.',
    ],
    signals: [
      'Data scale: 3,500 synthetic records · 24 features.',
      'Review focus: digital wellbeing · screen time · synthetic data · high-risk flag · risk prediction.',
    ],
    stack: ['Python', 'Pandas', 'Synthetic Data', 'Dataset'],
    tags: ['Synthetic Data', 'Mental Health', 'Digital Wellbeing', 'Risk Modeling'],
    repo: 'digital-lifestyle-benchmark-dataset',
    imageBase: 'Digital Lifestyle Benchmark Dataset',
    alt: {
      href: 'https://www.kaggle.com/datasets/tarekmasryo/digital-health-and-mental-wellness',
      label: 'Kaggle Dataset',
    },
    impact: '3,500 synthetic records · 24 features.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:hospital',
    type: 'Dataset',
    title: 'Hospital Deterioration Dataset',
    desc: 'Simulated hospital deterioration dataset for early-warning modeling with hourly vitals/labs and a next-12h target.',
    priority: 60,
    problem:
      'Early-warning modeling needs patient-level temporal data with hourly vitals/labs and a next-12h target to test leakage-safe deterioration workflows.',
    approach: [
      'Simulates admissions with hourly clinical signals across a 72h cohort for early-warning experiments.',
      'Structures labels and splits to support reproducible baseline modeling and dashboard workflows.',
    ],
    signals: [
      'Data scale: 10,000 admissions · hourly vitals/labs over a 72h cohort.',
      'Review focus: clinical time series · label quality · reproducible splits · ML-ready structure.',
    ],
    stack: ['Python', 'Pandas', 'Clinical Time Series', 'Dataset'],
    tags: ['Clinical Dataset', 'Time Series', 'Early Warning', 'Patient Deterioration'],
    repo: 'hospital-deterioration-dataset',
    imageBase: 'Hospital Deterioration Dataset',
    alt: {
      href: 'https://github.com/tarekmasryo/hospital-deterioration-next-12h-early-warning-baseline',
      label: 'Baseline',
    },
    impact: '10,000 admissions · hourly vitals/labs over a 72h cohort.',
  },
  {
    cat: 'analytics',
    icon: 'lucide:trophy',
    type: 'Dataset',
    title: 'Football Matches Dataset 2025',
    desc: 'European football matches dataset for 2024/2025 season analysis and dashboard workflows.',
    priority: 58,
    problem:
      'Sports analytics dashboards need clean match-level data with derived features before standings, team comparison, and season review views can be built.',
    approach: [
      'Packages European football match data into dashboard-ready tables for the 2024/2025 season.',
      'Includes derived features and match-level structure for team explorer, league comparison, and season analysis workflows.',
    ],
    signals: [
      'Data scale: 1,941 matches across top European leagues and UCL.',
      'Review focus: match results · derived features · season analysis · dashboard-ready sports data.',
    ],
    stack: ['Python', 'Pandas', 'Sports Analytics', 'Dataset'],
    tags: ['Football Dataset', 'Sports Analytics', 'Match Results', 'Feature Set'],
    repo: 'football-matches-2025-dataset',
    imageBase: 'Football Matches Dataset 2025',
    alt: {
      href: 'https://www.kaggle.com/datasets/tarekmasryo/football-matches-20242025-top-5-leagues',
      label: 'Kaggle Dataset',
    },
    impact: '1,941 matches across top European leagues and UCL.',
  },
  {
    cat: 'genai',
    icon: 'lucide:network',
    type: 'Dataset',
    title: 'GenAI Tools & Platforms Data',
    desc: 'Dataset mapping generative AI tools and platforms for comparison, taxonomy, API coverage, and landscape analysis.',
    priority: 56,
    problem:
      'The GenAI tooling landscape is difficult to compare without a structured taxonomy for categories, modalities, API coverage, and open-source signals.',
    approach: [
      'Maps GenAI tools and platforms into comparison-ready fields for landscape analysis and taxonomy review.',
      'Captures modality, category, open-source/API flags, and platform attributes for market and tooling research.',
    ],
    signals: [
      'Data scale: 113 tools · 22 columns.',
      'Review focus: tool categories · modality taxonomy · open-source/API flags · platform mapping.',
    ],
    stack: ['Python', 'Pandas', 'Dataset', 'Market Research'],
    tags: ['GenAI Landscape', 'Tools Dataset', 'Market Research'],
    repo: 'genai-tools-platforms-data',
    imageBase: 'GenAI Tools & Platforms Data',
    alt: {
      href: 'https://www.kaggle.com/datasets/tarekmasryo/generative-ai-tools-and-platforms-2025',
      label: 'Kaggle Dataset',
    },
    impact: '113 tools · 22 columns.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:stethoscope',
    type: 'Dataset',
    title: 'Cancer Risk Factors Data',
    desc: 'Cancer risk factors dataset for lifestyle, environment, genetics, and derived risk labels.',
    priority: 54,
    problem:
      'Cancer risk analysis needs a documented feature table that separates lifestyle, environmental, genetic, and derived risk fields for leakage-aware use.',
    approach: [
      'Provides a clean tabular dataset with data dictionary support for feature analysis and educational risk modeling.',
      'Documents derived risk labels so users can avoid leakage when building predictive baselines.',
    ],
    signals: [
      'Data scale: 2,000 rows × 21 columns.',
      'Review focus: medical risk factors · data dictionary · feature analysis · leakage-aware use.',
    ],
    stack: ['Python', 'Pandas', 'Healthcare Dataset', 'Data Dictionary'],
    tags: ['Healthcare Dataset', 'Cancer Risk', 'Feature Engineering', 'Data Dictionary'],
    repo: 'cancer-risk-factors-data',
    imageBase: 'Cancer Risk Factors Data',
    alt: {
      href: 'https://www.kaggle.com/datasets/tarekmasryo/cancer-risk-factors-dataset',
      label: 'Kaggle Dataset',
    },
    impact: '2,000 rows × 21 columns.',
  },
  {
    cat: 'healthcare',
    icon: 'lucide:droplet',
    type: 'Dataset',
    title: 'Blood Donation Registry Dataset',
    desc: 'ML-ready synthetic blood donor registry dataset for donor eligibility, deferrals, country prevalence, RBC compatibility, and healthcare outreach analysis.',
    priority: 53,
    problem:
      'Donor outreach and compatibility analysis need structured donor eligibility, deferral, prevalence, and RBC compatibility fields in one ML-ready asset.',
    approach: [
      'Builds a synthetic donor registry around eligibility status, deferrals, country prevalence, RBC compatibility, and outreach analysis.',
      'Supports both healthcare analytics and decision-policy notebooks without exposing real donor data.',
    ],
    signals: [
      'Operational signals: donor eligibility · deferrals · RBC compatibility · country prevalence · outreach modeling · healthcare operations.',
      'Review focus: blood donation · synthetic healthcare data · donor registry analysis.',
    ],
    stack: ['Python', 'Pandas', 'Healthcare Dataset', 'Synthetic Data'],
    tags: ['Blood Donation', 'Synthetic Data', 'Healthcare Analytics', 'Donor Registry'],
    repo: 'blood-donation-registry-dataset',
    imageBase: 'Blood Donation Registry Dataset',
    alt: {
      href: 'https://github.com/tarekmasryo/global-blood-donation-registry',
      label: 'Policy Project',
    },
    impact:
      'Donor eligibility, deferrals, RBC compatibility, country prevalence, and outreach modeling.',
  },
  {
    cat: 'genai',
    icon: 'lucide:image',
    type: 'Computer Vision App',
    title: 'Old Photo Restorer',
    desc: 'User-facing AI image restoration app using GFPGAN and Gradio, with restoration presets, strength control, optional upscaling, before/after preview, and batch ZIP export.',
    priority: 52,
    problem:
      'Photo restoration tools need controllable enhancement and before/after review so users can judge output quality before exporting results.',
    approach: [
      'Uses GFPGAN-based face restoration with presets and strength control for user-facing enhancement.',
      'Keeps optional upscaling separate from restoration so output quality and resolution can be controlled independently.',
      'Adds before/after preview and batch ZIP export to make the workflow practical for multiple images.',
    ],
    signals: [
      'Operational signals: restoration presets · strength control · optional upscaling · before/after preview · batch ZIP export.',
      'Review focus: image restoration · face enhancement · Gradio user workflow.',
    ],
    stack: ['Python', 'Gradio', 'GFPGAN', 'Image Restoration', 'Computer Vision'],
    tags: ['Image Restoration', 'Face Restoration', 'GenAI App', 'Gradio', 'Computer Vision'],
    repo: 'Old-Photo-Restorer',
    imageBase: 'Old Photo Restorer',
    impact:
      'User-facing image-restoration app with before/after review, presets, and batch ZIP export.',
  },
  {
    cat: 'analytics',
    icon: 'lucide:plug',
    type: 'Dashboard',
    title: 'EV Charging Dashboard',
    desc: 'Streamlit EV charging analytics dashboard for global map clustering, KPIs, country/power-class filters, and fast-DC allocation optimization.',
    priority: 50,
    problem:
      'EV planning workflows need map-first exploration, KPI slices, and expansion scenarios to compare charging coverage and fast-DC opportunities.',
    approach: [
      'Organizes EV infrastructure data into map-oriented and KPI-oriented views for regional comparison and charging-power analysis.',
      'Adds country/power-class filters plus a fast-DC allocation optimizer to compare expansion scenarios.',
      'Supports planning-style review through global map clustering, KPI tracking, and exportable views.',
    ],
    signals: [
      'Operational signals: global map clustering · KPIs · country filters · power-class filters · fast-DC allocation optimizer.',
      'Review focus: geospatial dashboard · station coverage · charging power classes · infrastructure planning.',
    ],
    stack: ['Python', 'Streamlit', 'Plotly', 'PyDeck', 'Pandas'],
    tags: ['EV Charging', 'Geospatial Analytics', 'Dashboard', 'Optimization'],
    repo: 'ev-charging-dashboard',
    imageBase: 'EV Charging Dashboard',
    impact:
      'Interactive EV infrastructure dashboard for coverage analysis and fast-DC allocation scenarios.',
  },
  {
    cat: 'analytics',
    icon: 'lucide:trophy',
    type: 'Dashboard',
    title: 'Football Matches Dashboard',
    desc: 'Football matches analytics dashboard for the 2024/2025 season with KPIs, standings, team explorer, head-to-head comparison, and interactive match tables.',
    priority: 48,
    problem:
      'Football match data becomes easier to analyze when standings, team comparison, head-to-head views, and match tables are combined into one interactive dashboard.',
    approach: [
      'Builds KPI cards, standings, team explorer, and head-to-head comparison from match-level season data.',
      'Uses interactive filters and match tables to support league, team, and season-level review.',
    ],
    signals: [
      'Operational signals: KPIs · standings · team explorer · head-to-head comparison · interactive match tables · season insights.',
      'Review focus: football analytics · sports dashboard · data visualization.',
    ],
    stack: ['Python', 'Streamlit', 'Plotly', 'Pandas'],
    tags: ['Football Analytics', 'Sports Dashboard', 'Data Visualization'],
    repo: 'football-matches-dashboard',
    imageBase: 'Football Matches Dashboard',
    alt: {
      href: 'https://github.com/tarekmasryo/football-matches-2025-dataset',
      label: 'Dataset',
    },
    impact:
      'Sports analytics dashboard for match exploration, standings review, and team-level comparison.',
  },
  {
    cat: 'analytics',
    icon: 'lucide:palette',
    type: 'Visual Lab',
    title: 'Seaborn + Matplotlib Visual Lab',
    desc: 'Interactive Streamlit lab to build, compare, and export Seaborn vs Matplotlib charts with UI controls, generated code snippets, and PNG/ZIP export.',
    priority: 46,
    problem:
      'Learning and comparing Python plotting libraries is easier when users can adjust chart controls, see the output, and export generated code from one interface.',
    approach: [
      'Provides an interactive Streamlit lab for building and comparing Seaborn and Matplotlib charts.',
      'Generates code snippets and supports PNG/ZIP export so visual experiments can be reused outside the app.',
      'Structures the UI around chart controls and visual diagnostics rather than static examples only.',
    ],
    signals: [
      'Operational signals: UI controls · generated code snippets · chart comparison · PNG export · ZIP export · visual diagnostics.',
      'Review focus: data visualization · plotting lab · EDA workflow.',
    ],
    stack: ['Python', 'Streamlit', 'Matplotlib', 'Seaborn', 'Plotly'],
    tags: ['Data Visualization', 'Plotting Lab', 'EDA', 'Python'],
    repo: 'seaborn-matplotlib-visual-lab',
    imageBase: 'Seaborn + Matplotlib Visual Lab',
    impact:
      'Interactive plotting lab for learning, comparing, and exporting Python visualization patterns.',
  },
  {
    cat: 'genai',
    icon: 'lucide:tool',
    type: 'Developer Tool',
    title: 'QuickStart',
    desc: 'Developer tooling project for generating quick artifacts and reusable scaffolds from Hugging Face URLs.',
    priority: 44,
    problem:
      'Developers often lose time turning Hugging Face URLs into usable local commands, file views, and starter scaffolds.',
    approach: [
      'Inspects Hugging Face-style repository URLs and generates quick commands, download snippets, file views, and reusable scaffolds.',
      'Wraps the workflow in a Gradio interface so users can move from URL to working artifact faster.',
    ],
    signals: [
      'Operational signals: repository inspection · Hugging Face URL workflow · artifact generation · reusable scaffolds · automation.',
      'Review focus: developer tools · Hugging Face workflows · scaffolding.',
    ],
    stack: ['Python', 'Gradio', 'Hugging Face Hub', 'Automation'],
    tags: ['Developer Tools', 'Hugging Face', 'Scaffolding', 'Automation'],
    repo: 'QuickStart',
    imageBase: 'QuickStart',
    impact:
      'Developer tooling for generating quick artifacts and scaffolds from Hugging Face URLs.',
  },
];
